---
# Server configuration
timezone: Europe/London

# Package version
php_version: 7.2
mariadb_version: 10.1

# Nginx configuration
server_hostname: yourdomain.co.uk
magento_dir: /var/www/html/magento

# Database configuration
db_host: localhost
db_name: magento
db_user: magento
db_password: magento

# Magento configuration
magento_public_key: MAGENTO_PUBLIC_KEY
magento_private_key: MAGENTO_PRIVATE_KEY

magento_mode: default

base_url: http://yourdomain.co.uk/
use_rewrites: 1

language: en_GB
currency: GBP

backend_frontname: admin
admin_firstname: admin
admin_lastname: admin
admin_email: admin@admin.com
admin_user: admin
admin_password: admin123
